import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ElementNode, ExtractionResult } from "./schema.js";
import { loadExtraction, sourceDir } from "./store.js";
import { SiteForgeException } from "./errors.js";

export interface DesignTokens {
  colors: string[];
  fonts: string[];
  fontSizes: string[];
  cssVariables: Record<string, string>;
  snippet: string;
}

export interface ExportDesignTokensResult {
  ok: true;
  sourceId: string;
  tokens: DesignTokens;
  paths: {
    json: string;
    css: string;
  };
}

function walkCollect(
  node: ElementNode,
  colors: Set<string>,
  fonts: Set<string>,
  fontSizes: Set<string>,
): void {
  const s = node.styles ?? {};
  for (const key of ["color", "backgroundColor", "borderTopColor"] as const) {
    const v = s[key];
    if (v && v !== "rgba(0, 0, 0, 0)" && v !== "transparent") colors.add(v);
  }
  if (s.fontFamily) fonts.add(s.fontFamily);
  if (s.fontSize) fontSizes.add(s.fontSize);
  for (const c of node.children ?? []) walkCollect(c, colors, fonts, fontSizes);
}

function extractCssVarsFromTree(root: ElementNode): Record<string, string> {
  const vars: Record<string, string> = {};
  function walk(n: ElementNode): void {
    for (const [k, v] of Object.entries(n.styles ?? {})) {
      if (k.startsWith("--")) vars[k] = v;
    }
    for (const c of n.children ?? []) walk(c);
  }
  walk(root);
  return vars;
}

export function designTokensFromExtraction(
  extraction: ExtractionResult,
): DesignTokens {
  const colors = new Set<string>();
  const fonts = new Set<string>();
  const fontSizes = new Set<string>();
  walkCollect(extraction.root, colors, fonts, fontSizes);
  const cssVariables = extractCssVarsFromTree(extraction.root);

  const colorList = [...colors].slice(0, 40);
  const fontList = [...fonts].slice(0, 12);
  const sizeList = [...fontSizes].slice(0, 20);

  const lines: string[] = [":root {"];
  colorList.forEach((c, i) => {
    lines.push(`  --sf-color-${i + 1}: ${c};`);
  });
  fontList.forEach((f, i) => {
    lines.push(`  --sf-font-${i + 1}: ${f};`);
  });
  sizeList.forEach((s, i) => {
    lines.push(`  --sf-font-size-${i + 1}: ${s};`);
  });
  for (const [k, v] of Object.entries(cssVariables)) {
    lines.push(`  ${k}: ${v};`);
  }
  lines.push("}");
  lines.push("");
  lines.push(
    "/* Generated by SiteForge export_design_tokens — review before commit */",
  );

  return {
    colors: colorList,
    fonts: fontList,
    fontSizes: sizeList,
    cssVariables,
    snippet: lines.join("\n"),
  };
}

/**
 * Export design tokens (colors/fonts) from a stored extraction into JSON + CSS snippet.
 */
export async function exportDesignTokens(
  outDir: string,
  sourceId: string,
  targetDir?: string,
): Promise<ExportDesignTokensResult> {
  let extraction: ExtractionResult;
  try {
    extraction = await loadExtraction(outDir, sourceId);
  } catch {
    throw new SiteForgeException(
      "SOURCE_NOT_FOUND",
      `Source not found: ${sourceId}`,
    );
  }

  const tokens = designTokensFromExtraction(extraction);
  const dir = targetDir ?? path.join(sourceDir(outDir, sourceId), "tokens");
  await mkdir(dir, { recursive: true });
  const jsonPath = path.join(dir, "design-tokens.json");
  const cssPath = path.join(dir, "design-tokens.css");
  const { snippet: _snippet, ...rest } = tokens;
  await writeFile(
    jsonPath,
    JSON.stringify({ sourceId, ...rest }, null, 2),
    "utf8",
  );
  await writeFile(cssPath, tokens.snippet, "utf8");

  return {
    ok: true,
    sourceId,
    tokens,
    paths: { json: jsonPath, css: cssPath },
  };
}
